{{- if .Values.serviceMonitor.enabled -}}
# service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.serviceMonitor.name | default "rundeck-exporter-monitor" }}
  namespace: {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "rundeck-exporter.selectorLabels" . | nindent 4 }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
      port: metrics
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout  }}
  selector:
    matchLabels:
      {{- include "rundeck-exporter.selectorLabels" . | nindent 8 }}
{{- end }}
